name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-aarch64:
    runs-on: [ self-hosted, ARM64 ] 

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make


  build-x86_64:
    runs-on: [ self-hosted, X64 ] 

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
