name: Build check

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ "main" ]

jobs:
  x86_64-cross-riscv64:
    runs-on: [ self-hosted, X64 ]

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.ARANCINI_TOKEN }}
      - name: nix build
        run: nix build .#crossPackage.riscv64-linux

  aarch64:
    runs-on: [ self-hosted, ARM64 ]

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.ARANCINI_TOKEN }}
      - name: nix build
        run: nix build .#defaultPackage.aarch64-linux

      - name: hello-world
        run: nix develop --command bash -c "./result/bin/txlat -I ./result/test/hello-world/hello-static-musl -O bin.out && ./bin.out 2> /dev/null"
